# Generated by Django 5.2.2 on 2025-06-13 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='plack_player',
            new_name='black_player',
        ),
    ]
